### PR TITLE
LPS-73343 Using bad portlet id in dynamic-data-mapping/dynamic-data-mapping-taglib module

### PR DESCRIPTION
**Pull request by zsagia**
Hi Dustin,

Based on your proposal I made a newer and better fix for LPS-72761. I managed to find the root of this and I'd like to inform you that portal code contains many similar cases where we can face with the same mistake.
We need to fix this kind of mistakes(We are using portletDisplay.getRootPortletId() instead of portletDisplay.getId()) in lots of places in our portal code.
This pull contains a fix for the first place because this is related to LPS-72761. LPS-72761 depends on this fix and it will be work correctly if this fix is already merged to portal code.

I added reproduction steps to the LPS please check it.

Please let me know id I wasn't very detailed.

Thanks in advance,
Zsaga

### CODE REVIEW

**Comment by zsagia** [comment]
Hi Dustin,

I sent this pull last week to your com-liferay-dynamic-data-mapping sub-repo. I saw the source-format error but I think that is not related with my modification.

Do you have any idea about it?

Thanks,
 Zsaga

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zsagia** [comment]
Hi Dustin,

Yes, I tested it of course(always) :)

**Pull request closed without merging**
